- hosts: all
  become: false
  gather_facts: false
  tasks:
  - name: Clone VM with only source VM name.
    community.general.proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: 9ca17a0c-48b9-4112-8aa0-cafdecaf9d91
      api_host: 194.26.17.202
      node: test-pve
      clone: "{{ template_vmname }}" 
      name: "{{ template_vmname }}_{{ ansible_date_time.epoch | int | to_datetime | strftime('%d%m%Y%H%M%S') }}"
      pool: test
