- hosts: proxmox
  become: false
  gather_facts: false
  vars: 
    template_name: "{{ template_name }}"
    new_vm_prefix: "VM-"
  tasks:
  - name: Check incoming template_name
    debug:
      msg: "Incoming name: {{ template_name }}"
  - name: Get next VM ID
    register: nextid
    command: "pvesh get /cluster/nextid"
  - set_fact:
      newid: "{{ nextid.stdout | regex_replace('(\\W+)') | int }}"
  - name: Clone a full clone of the template VM
    community.general.proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: 9ca17a0c-48b9-4112-8aa0-cafdecaf9d91
      api_host: 194.26.17.202
      node: test-pve
      newid: "{{ newid }}"
      clone: "{{ template_name }}" 
      full: true
      name: "{{ new_vm_prefix }}-test"
      state: present
    register: clone_output
  - name: Display the new VM ID
    debug:
      var: "{{ clone_output.vmid }}"
