- hosts: proxmox
  become: false
  gather_facts: false
  tasks:
  - name: Forward test-pve port to VM ip
    ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      in_interface: eth0
      protocol: tcp
      to_destination: "{{ vmip }}:{{ vmport }} --dport {{ dport }} -j DNAT"
    become: yes
