- hosts: proxmox
  become: false
  gather_facts: false
  tasks:
  - name: Forward test-pve port to VM ip
    ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      match: tcp
      destination_port: "{{ dport }}"
      jump: DNAT
      to_destination: "{{ vmip }}:{{ vmport }}"
    become: yes
